export const fieldStats = [
    { id: '1', label: 'Soil Moisture', value: '68%', unit: '', icon: 'droplets', trend: 'up', color: '#3b82f6' },
    { id: '2', label: 'Avg Temp', value: '21.4', unit: '°C', icon: 'thermometer', trend: 'stable', color: '#f59e0b' },
    { id: '3', label: 'Rainfall 7d', value: '12.3', unit: 'mm', icon: 'cloud-rain', trend: 'down', color: '#6366f1' },
    { id: '4', label: 'Wind Speed', value: '14', unit: 'km/h', icon: 'wind', trend: 'up', color: '#10b981' },
    { id: '5', label: 'UV Index', value: '6.2', unit: '', icon: 'sun', trend: 'stable', color: '#f59e0b' },
    { id: '6', label: 'Humidity', value: '74%', unit: '', icon: 'gauge', trend: 'up', color: '#8b5cf6' },
  ];
  
  export const predictions = [
    {
      id: '1',
      crop: 'Corn',
      variety: 'DKC 6088',
      status: 'optimal',
      statusLabel: 'Optimal Window',
      probability: 87,
      sowingDate: 'April 18–22',
      harvestDate: 'Sept 12–18',
      lossAvoidance: '€15,400',
      yieldBoost: '+23%',
      risks: [
        { label: 'Late Frost', level: 'low', value: 8 },
        { label: 'Drought Stress', level: 'medium', value: 34 },
        { label: 'Flood Risk', level: 'low', value: 12 },
        { label: 'Hail Exposure', level: 'low', value: 5 },
      ],
      insights: [
        'Soil temperature will reach optimal 10°C germination threshold by April 17.',
        'Extended dry spell forecasted post-week 2, ideal for root establishment.',
        'No significant frost events in 21-day outlook for your region.',
      ],
    },
    {
      id: '2',
      crop: 'Wheat',
      variety: 'KWS Barrel',
      status: 'risk',
      statusLabel: 'High Risk',
      probability: 31,
      sowingDate: 'May 5–10',
      harvestDate: 'Aug 20–26',
      lossAvoidance: '€6,200',
      yieldBoost: '-8%',
      risks: [
        { label: 'Late Frost', level: 'high', value: 78 },
        { label: 'Drought Stress', level: 'high', value: 62 },
        { label: 'Flood Risk', level: 'medium', value: 41 },
        { label: 'Hail Exposure', level: 'medium', value: 38 },
      ],
      insights: [
        'Frost probability exceeds 70% through end of April.',
        'Soil moisture deficit developing — irrigation may be required.',
        'Recommend delaying sowing by 12–18 days for risk mitigation.',
      ],
    },
    {
      id: '3',
      crop: 'Soybeans',
      variety: 'Suedina 004',
      status: 'optimal',
      statusLabel: 'Optimal Window',
      probability: 79,
      sowingDate: 'May 2–7',
      harvestDate: 'Oct 8–14',
      lossAvoidance: '€9,800',
      yieldBoost: '+17%',
      risks: [
        { label: 'Late Frost', level: 'low', value: 11 },
        { label: 'Drought Stress', level: 'medium', value: 28 },
        { label: 'Flood Risk', level: 'low', value: 9 },
        { label: 'Hail Exposure', level: 'low', value: 7 },
      ],
      insights: [
        'Post-May 1 soil temps consistently above 12°C minimum for germination.',
        'Photosynthetic conditions favorable for early vegetative growth.',
        'Low risk window extends through May 12 based on ensemble models.',
      ],
    },
  ];
  
  export const temperatureHistory = [
    { year: 2004, avgTemp: 9.2, maxTemp: 32.1, minTemp: -8.4, anomaly: -0.8 },
    { year: 2005, avgTemp: 9.8, maxTemp: 33.4, minTemp: -7.1, anomaly: -0.2 },
    { year: 2006, avgTemp: 10.6, maxTemp: 35.7, minTemp: -6.8, anomaly: 0.6 },
    { year: 2007, avgTemp: 11.1, maxTemp: 34.9, minTemp: -5.3, anomaly: 1.1 },
    { year: 2008, avgTemp: 9.4, maxTemp: 31.2, minTemp: -9.2, anomaly: -0.6 },
    { year: 2009, avgTemp: 10.2, maxTemp: 33.8, minTemp: -7.6, anomaly: 0.2 },
    { year: 2010, avgTemp: 8.9, maxTemp: 30.4, minTemp: -11.3, anomaly: -1.1 },
    { year: 2011, avgTemp: 10.8, maxTemp: 34.1, minTemp: -6.2, anomaly: 0.8 },
    { year: 2012, avgTemp: 11.3, maxTemp: 36.8, minTemp: -5.9, anomaly: 1.3 },
    { year: 2013, avgTemp: 9.7, maxTemp: 32.6, minTemp: -8.1, anomaly: -0.3 },
    { year: 2014, avgTemp: 11.6, maxTemp: 35.3, minTemp: -4.7, anomaly: 1.6 },
    { year: 2015, avgTemp: 12.1, maxTemp: 37.4, minTemp: -3.8, anomaly: 2.1 },
    { year: 2016, avgTemp: 11.9, maxTemp: 36.1, minTemp: -4.2, anomaly: 1.9 },
    { year: 2017, avgTemp: 11.4, maxTemp: 34.7, minTemp: -5.6, anomaly: 1.4 },
    { year: 2018, avgTemp: 12.8, maxTemp: 38.9, minTemp: -3.1, anomaly: 2.8 },
    { year: 2019, avgTemp: 12.3, maxTemp: 37.2, minTemp: -4.6, anomaly: 2.3 },
    { year: 2020, avgTemp: 13.1, maxTemp: 38.4, minTemp: -2.9, anomaly: 3.1 },
    { year: 2021, avgTemp: 10.9, maxTemp: 33.6, minTemp: -6.4, anomaly: 0.9 },
    { year: 2022, avgTemp: 13.4, maxTemp: 40.1, minTemp: -2.4, anomaly: 3.4 },
    { year: 2023, avgTemp: 13.8, maxTemp: 41.2, minTemp: -1.8, anomaly: 3.8 },
    { year: 2024, avgTemp: 14.2, maxTemp: 42.3, minTemp: -1.1, anomaly: 4.2 },
  ];
  
  export const monthlyForecast = [
    { month: 'Jan', temp: 2.1, rainfall: 48, frost: true },
    { month: 'Feb', temp: 3.4, rainfall: 42, frost: true },
    { month: 'Mar', temp: 7.8, rainfall: 38, frost: false },
    { month: 'Apr', temp: 12.4, rainfall: 44, frost: false },
    { month: 'May', temp: 17.2, rainfall: 52, frost: false },
    { month: 'Jun', temp: 21.8, rainfall: 61, frost: false },
    { month: 'Jul', temp: 24.3, rainfall: 55, frost: false },
    { month: 'Aug', temp: 23.7, rainfall: 49, frost: false },
    { month: 'Sep', temp: 18.9, rainfall: 47, frost: false },
    { month: 'Oct', temp: 13.1, rainfall: 56, frost: false },
    { month: 'Nov', temp: 6.8, rainfall: 63, frost: true },
    { month: 'Dec', temp: 2.9, rainfall: 51, frost: true },
  ];
  